# Generated by Django 3.2.11 on 2022-01-17 09:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('topic', models.CharField(max_length=150, verbose_name='Konu')),
                ('first_name', models.CharField(max_length=25, verbose_name='Adınız')),
                ('last_name', models.CharField(max_length=25, verbose_name='Soyadınız')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Telefon numaranızı başında sıfır olmadan: '5554443322' şeklinde giriniz.", regex='^\\+?1?\\d{9,10}$')], verbose_name='Telefon Numaranız')),
                ('message', models.TextField(max_length=700, verbose_name='Mesajınız')),
                ('publishing_date', models.DateTimeField(auto_now_add=True, verbose_name='Gönderilme Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('header', models.CharField(max_length=100, verbose_name='Başlık')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Fiyat')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('publishing_date', models.DateTimeField(auto_now_add=True, verbose_name='Yayımlanma Tarihi')),
                ('image', models.ImageField(upload_to='petshop_images', verbose_name='Fotoğraf')),
                ('active', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(default=1)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.age', verbose_name='Yaş')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.brand', verbose_name='Marka')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.breed', verbose_name='Tür')),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.foodtype', verbose_name='Mama Türü')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('header', models.CharField(max_length=100, verbose_name='Başlık')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('illness', models.CharField(max_length=50, verbose_name='Tanı/Hastalık')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Tedavi Ücreti')),
                ('paying_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ödenen Tutar')),
                ('publishing_date', models.DateTimeField(auto_now_add=True, verbose_name='Yayımlanma Tarihi')),
                ('image', models.ImageField(upload_to='treatment_images', verbose_name='Fotoğraf')),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.age', verbose_name='Yaş')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.breed', verbose_name='Tür')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.veterinaryclinic', verbose_name='Veteriner Kliniği')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_posts', to=settings.AUTH_USER_MODEL, verbose_name='Gönüllü')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts', models.ManyToManyField(to='pages.Post')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderItemUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('posts', models.ManyToManyField(to='pages.OrderItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='İsim')),
                ('content', models.TextField(verbose_name='Yorum')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pages.post')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pages.treatment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=25, verbose_name='Hayvanın ismi')),
                ('header', models.CharField(max_length=100, verbose_name='Başlık')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('publishing_date', models.DateTimeField(auto_now_add=True, verbose_name='Yayımlanma Tarihi')),
                ('image', models.ImageField(upload_to='treatment_images', verbose_name='Fotoğraf')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Telefon numaranızı başında sıfır olmadan: '5554443322' şeklinde giriniz.", regex='^\\+?1?\\d{9,10}$')], verbose_name='İletişim Numarası')),
                ('slug', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.age', verbose_name='Yaş')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.breed', verbose_name='Tür')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.gender', verbose_name='Cinsiyet')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='adoption_posts', to=settings.AUTH_USER_MODEL, verbose_name='Gönüllü')),
            ],
        ),
    ]
