# Generated by Django 3.2.11 on 2022-01-17 09:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VeterinaryClinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Klinik Adı')),
                ('adress', models.TextField(max_length=500, verbose_name='Adres')),
                ('phone_number', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon numaranızı başında sıfır olmadan: '5554443322' şeklinde giriniz.", regex='^\\+?1?\\d{9,10}$')], verbose_name='Telefon Numarası')),
                ('image', models.ImageField(upload_to='VeterinaryClinics/', verbose_name='Klinik Görseli')),
                ('account', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Bakiye')),
                ('publishing_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('slug', models.SlugField(unique=True)),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBanks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('feedbank_name', models.CharField(max_length=100, unique=True, verbose_name='Kumbara Adı')),
                ('adress', models.TextField(max_length=500, verbose_name='Adres')),
                ('phone_number', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon numaranızı başında sıfır olmadan: '5554443322' şeklinde giriniz.", regex='^\\+?1?\\d{9,10}$')], verbose_name='Telefon Numarası')),
                ('image', models.ImageField(upload_to='FeedBanks/', verbose_name='Kumbara Görseli')),
                ('publishing_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('content', models.TextField(max_length=500, verbose_name='Motivasyonunuz')),
                ('slug', models.SlugField(unique=True)),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='FeedBankProfile', to=settings.AUTH_USER_MODEL, verbose_name='Gönüllü')),
            ],
        ),
    ]
